---
deployment:
  tasks:
    - export DEPLOYPATH=/home/sewx2253/public_html/
    - /bin/cp index.html $DEPLOYPATH
    - /bin/cp -R assets $DEPLOYPATH
    - /bin/cp .htaccess $DEPLOYPATH
    - /bin/cp style.css $DEPLOYPATH
